
---
title: 'Risks to the Federal Government from Climate Impacts '
Authors: Ananya Vajpeyi & Molly Miller 
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}

#install.packages("tidyverse")
#install.packages("reprex", type = "binary")
library(readr)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(tibble)
#install.packages("ggrepel", type = "binary")
#install.packages("xfun", type = "binary")
library(ggrepel)

#FNMA_data <- read.delim("FNMA_total.txt")

fema <- read_csv("NRI_Table_CensusTracts.csv")

is.factor(fema$STATE)

#FHLMC_data <- read.delim("FHLMC_total.txt")

#FNMA_data


```

```{r}
#FNMA_tract <- FNMA_data %>% rename(US_Postal_State_Code = "US.Postal.State.Code") %>% group_by(US_Postal_State_Code, County, Census_Tract,) %>% summarise(n=n(), note_amount = sum(X.Note.amount), UPB_amount = sum(Acquisition.unpaid.principal.balance), High_DTI_note_amount = sum(X.Note.amount[Debt.to.income..DTI..ratio > 45]), High_DTI_UPB = sum(Acquisition.unpaid.principal.balance[Debt.to.income..DTI..ratio > 45]), LTV60orlower = sum(Loat.to.value.ration.at.origination.or.combined.LTV.where.available <= 60), LTV61_70 = sum(Loat.to.value.ration.at.origination.or.combined.LTV.where.available > 60 & Loat.to.value.ration.at.origination.or.combined.LTV.where.available <= 70), LTV71_80 = sum(Loat.to.value.ration.at.origination.or.combined.LTV.where.available > 70 & Loat.to.value.ration.at.origination.or.combined.LTV.where.available <= 80), LTV81_90 = sum(Loat.to.value.ration.at.origination.or.combined.LTV.where.available > 80 & Loat.to.value.ration.at.origination.or.combined.LTV.where.available <= 90), LTV91_100 = sum(Loat.to.value.ration.at.origination.or.combined.LTV.where.available > 90 & Loat.to.value.ration.at.origination.or.combined.LTV.where.available <= 100), LTVover100 = sum(Loat.to.value.ration.at.origination.or.combined.LTV.where.available > 100), DTI45orlower = sum(Debt.to.income..DTI..ratio <= 45), DTIover45 = sum(Debt.to.income..DTI..ratio > 45), DTStract = sum(X.Rural.Census.Tract == 1 | Lower.Mississippi.Delta.County == 1 | Middle.Appalachia.County == 1 | Persistent.Poverty.County == 1 | Area.of.concentrated.poverty == 1 | High.opportunity.area == 1 | Qualified.opportunity.zone.QOZ..Census.tract == 1))

#view(FNMA_tract)
#write.csv(FNMA_tract,"FNMA_by_censustract.csv")
```


```{r}
#FHLMC_tract <- FHLMC_data %>% rename(US_Postal_State_Code = "US.Postal.State.Code") %>% group_by(US_Postal_State_Code, County, Census.Tract) %>% summarise(n=n(), note_amount = sum(X.Note.amount), UPB_amount = sum(Acquisition.unpaid.principal.balance), High_DTI_note_amount = sum(X.Note.amount[Debt.to.income..DTI..ratio > 45]), High_DTI_UPB = sum(Acquisition.unpaid.principal.balance[Debt.to.income..DTI..ratio > 45]), LTV60orlower = sum(Loat.to.value.ration.at.origination.or.combined.LTV.where.available <= 60), LTV61_70 = sum(Loat.to.value.ration.at.origination.or.combined.LTV.where.available > 60 & Loat.to.value.ration.at.origination.or.combined.LTV.where.available <= 70), LTV71_80 = sum(Loat.to.value.ration.at.origination.or.combined.LTV.where.available > 70 & Loat.to.value.ration.at.origination.or.combined.LTV.where.available <= 80), LTV81_90 = sum(Loat.to.value.ration.at.origination.or.combined.LTV.where.available > 80 & Loat.to.value.ration.at.origination.or.combined.LTV.where.available <= 90), LTV91_100 = sum(Loat.to.value.ration.at.origination.or.combined.LTV.where.available > 90 & Loat.to.value.ration.at.origination.or.combined.LTV.where.available <= 100), LTVover100 = sum(Loat.to.value.ration.at.origination.or.combined.LTV.where.available > 100), DTI45orlower = sum(Debt.to.income..DTI..ratio <= 45), DTIover45 = sum(Debt.to.income..DTI..ratio > 45), DTStract = sum(X.Rural.Census.Tract == 1 | Lower.Mississippi.Delta.County == 1 | Middle.Appalachia.County == 1 | Persistent.Poverty.County == 1 | Area.of.concentrated.poverty == 1 | High.opportunity.area == 1 | Qualified.opportunity.zone.QOZ..Census.tract == 1))

#view(FHLMC_tract)
#write.csv(FHLMC_tract,"FHLMC_by_tract.csv")
```

```{r}

weather_risk <- fema %>%
  group_by(STATE) %>% 
  summarise(
    FiveRisk = sum(ANYFIVERISK>0)/n()*100,
    MORTGAGE_VALUE = sum(Total_UPB),
    MORTGAGE_VALUE_hnhr = sum(Total_UPB[HIGHNEED_HIGHRISK>0]),
    HIGHDTI_UPB_value = sum(`Total High_DTI_UPB`),
    HIGHDTI_UPB_value_hnhr = sum(`Total High_DTI_UPB`[HIGHNEED_HIGHRISK>0]),
    Percent_HighDTI = sum(Total_DTIover45)/sum(MORTGAGE_COUNT)*100,
    highneedhighrisk = sum(HIGHNEED_HIGHRISK)/n()*100)
weather_risk
```

```{r}
Five_Risk <- weather_risk %>%
  filter(FiveRisk>0)
Five_Risk

median <- Five_Risk %>% 
  summarise(medFiveRisk = median(FiveRisk),
            medMORTGAGE_VALUE = median(MORTGAGE_VALUE),
            medPercent_HighDTI = median(Percent_HighDTI),
            medhighneedhighrisk = median(highneedhighrisk),
            medMORTGAGE_VALUE_hnhr = median(MORTGAGE_VALUE_hnhr),
            medHIGHDTI_UPB_value = median(HIGHDTI_UPB_value),
            medHIGHDTI_UPB_value_hnhr = median(HIGHDTI_UPB_value_hnhr)
            )
view(median)

```

```{r}
Five_Risk <- weather_risk %>%
  filter(FiveRisk>0)
ggplot(data = Five_Risk, mapping = aes(x = FiveRisk, y = MORTGAGE_VALUE))+
  geom_point()+
  geom_point(data = subset(weather_risk, (FiveRisk>(median(FiveRisk)) & MORTGAGE_VALUE>median(MORTGAGE_VALUE)) | STATE == "California"), segment.color = 'grey80', colour = "red")+
  theme_classic()+
  labs(x = '% of Census Tracts with High Climate Risk', y = 'Value of Unpaid Principal Balance')+
  geom_text_repel(data = subset(weather_risk, (FiveRisk>(median(FiveRisk)) & MORTGAGE_VALUE>median(MORTGAGE_VALUE)) | STATE == "California"), aes(label = STATE), segment.color = 'grey80', colour = "red")+
  geom_vline(data = median, mapping = aes(xintercept = medFiveRisk))+
  geom_hline(data = median, mapping = aes(yintercept = medMORTGAGE_VALUE))+
  scale_y_continuous(labels=scales::dollar_format())
```
```{r}

Five_Risk <- weather_risk %>%
  filter(FiveRisk>0)
ggplot(data = Five_Risk, mapping = aes(x = highneedhighrisk, y = Percent_HighDTI))+
  geom_point()+
  theme_classic()+
  labs(x = '% of Census Tracts that are HNHR', y = '% of Mortgages with High DTI Ratios')+
  geom_text_repel(data = subset(weather_risk, (highneedhighrisk>(median(highneedhighrisk)) & Percent_HighDTI>median(Percent_HighDTI))), aes(label = STATE), segment.color = 'grey80', colour = "red")+
  geom_vline(data = median, mapping = aes(xintercept = medhighneedhighrisk))+
  geom_hline(data = median, mapping = aes(yintercept = medPercent_HighDTI))

```

```{r}
Five_Risk <- weather_risk %>%
  filter(FiveRisk>0)
ggplot(data = Five_Risk, mapping = aes(x = highneedhighrisk, y = HIGHDTI_UPB_value_hnhr))+
  geom_point()+
  theme_classic()+
  labs(x = '% of Census Tracts that are HNHR', y = 'Value of High DTI Unpaid Principal Balance in HNHR Tracts')+
  geom_text_repel(data = subset(weather_risk, (highneedhighrisk>(median(highneedhighrisk)) & HIGHDTI_UPB_value_hnhr>median(HIGHDTI_UPB_value_hnhr)) | STATE == "California"), aes(label = STATE), segment.color = 'grey80', colour = "red")+
  geom_vline(data = median, mapping = aes(xintercept = medhighneedhighrisk))+
  geom_hline(data = median, mapping = aes(yintercept = medHIGHDTI_UPB_value_hnhr))+
  scale_y_continuous(labels=scales::dollar_format())
```
```{r}
Five_Risk <- weather_risk %>%
  filter(FiveRisk>0)
ggplot(data = Five_Risk, mapping = aes(x = highneedhighrisk, y = HIGHDTI_UPB_value))+
  geom_point()+
  theme_classic()+
  labs(x = '% of Census Tracts that are HNHR', y = 'Value of High DTI Unpaid Principal Balance')+
  geom_text_repel(data = subset(weather_risk, (highneedhighrisk>(median(highneedhighrisk)) & HIGHDTI_UPB_value>median(HIGHDTI_UPB_value)) | STATE == "California"), aes(label = STATE), segment.color = 'grey80', colour = "red")+
  geom_vline(data = median, mapping = aes(xintercept = medhighneedhighrisk))+
  geom_hline(data = median, mapping = aes(yintercept = medHIGHDTI_UPB_value))+
  scale_y_continuous(labels=scales::dollar_format())
```

```{r}

weather_risk_florida <- fema %>%
  filter(STATE=="Florida") %>% 
  group_by(COUNTY) %>% 
  summarise(
    FiveRisk = sum(ANYFIVERISK>0)/n()*100,
    MORTGAGE_VALUE = sum(Total_UPB),
    MORTGAGE_VALUE_hnhr = sum(Total_UPB[HIGHNEED_HIGHRISK>0]),
    HIGHDTI_UPB_value = sum(`Total High_DTI_UPB`),
    HIGHDTI_UPB_value_hnhr = sum(`Total High_DTI_UPB`[HIGHNEED_HIGHRISK>0]),
    Percent_HighDTI = sum(Total_DTIover45)/sum(MORTGAGE_COUNT)*100,
    highneedhighrisk = sum(HIGHNEED_HIGHRISK)/n()*100)
weather_risk_florida
```


```{r}
topHNHRvalue <- weather_risk_florida %>% 
  filter(MORTGAGE_VALUE_hnhr>500000000)
ggplot(data = topHNHRvalue, mapping = aes(x= MORTGAGE_VALUE_hnhr, y= fct_reorder(COUNTY,MORTGAGE_VALUE_hnhr)))+
  geom_col() + 
  theme_classic()+
  theme(axis.text.y = element_text(size=14, vjust = 0.2, hjust=0.2))+ 
  labs(
    x= "UPB Value in HNHR census tracts",
    y= "Counties")+
  geom_label(aes(label=scales::dollar(MORTGAGE_VALUE_hnhr)), position=position_dodge(width=0.9), hjust=1, vjust=-0.25)+
  guides(color=FALSE)+
  scale_x_continuous(labels=scales::dollar_format())
```


```{r}
Florida_median <- weather_risk_florida %>% 
  summarise(medFiveRisk = median(FiveRisk),
            medMORTGAGE_VALUE = median(MORTGAGE_VALUE),
            medPercent_HighDTI = median(Percent_HighDTI),
            medhighneedhighrisk = median(highneedhighrisk),
            medMORTGAGE_VALUE_hnhr = median(MORTGAGE_VALUE_hnhr),
            medHIGHDTI_UPB_value = median(HIGHDTI_UPB_value),
            medHIGHDTI_UPB_value_hnhr = median(HIGHDTI_UPB_value_hnhr)
            )
view(Florida_median)
```

```{r}
ggplot(data = weather_risk_florida, mapping = aes(x = FiveRisk, y = MORTGAGE_VALUE))+
  geom_point()+
  theme_classic()+
  labs(x = '% of Census Tracts with High Climate Risk', y = 'Value of Unpaid Principal Balance')+
  geom_text_repel(data = subset(weather_risk_florida, (FiveRisk>(median(FiveRisk)) & MORTGAGE_VALUE>median(MORTGAGE_VALUE))), aes(label = COUNTY), segment.color = 'grey80', colour = "red")+
  geom_vline(data = Florida_median, mapping = aes(xintercept = medFiveRisk))+
  geom_hline(data = Florida_median, mapping = aes(yintercept = medMORTGAGE_VALUE))+
  scale_y_continuous(labels=scales::dollar_format())
```

```{r}
ggplot(data = weather_risk_florida, mapping = aes(highneedhighrisk, y = MORTGAGE_VALUE))+
  geom_point()+
  theme_classic()+
  labs(x = '% of Census Tracts that are HNHR', y = 'Value of Unpaid Principal Balance')+
  geom_text_repel(data = subset(weather_risk_florida, (highneedhighrisk>(median(highneedhighrisk)) & MORTGAGE_VALUE>median(MORTGAGE_VALUE))), aes(label = COUNTY), segment.color = 'grey80', colour = "red")+
  geom_vline(data = Florida_median, mapping = aes(xintercept = medhighneedhighrisk))+
  geom_hline(data = Florida_median, mapping = aes(yintercept = medMORTGAGE_VALUE))+
  scale_y_continuous(labels=scales::dollar_format())
```

```{r}
ggplot(data = weather_risk_florida, mapping = aes(x = highneedhighrisk, y = MORTGAGE_VALUE_hnhr))+
  geom_point()+
  theme_classic()+
  labs(x = '% of Census Tracts that are HNHR', y = 'Value of Unpaid Principal Balance in HNHR Tracts')+
  geom_text_repel(data = subset(weather_risk_florida, (highneedhighrisk>(median(highneedhighrisk)) & MORTGAGE_VALUE_hnhr>median(MORTGAGE_VALUE_hnhr))), aes(label = COUNTY), segment.color = 'grey80', colour = "red")+
  geom_vline(data = Florida_median, mapping = aes(xintercept = medhighneedhighrisk))+
  geom_hline(data = Florida_median, mapping = aes(yintercept = medMORTGAGE_VALUE_hnhr))+
  scale_y_continuous(labels=scales::dollar_format())
```


```{r}
ggplot(data = weather_risk_florida, mapping = aes(x = highneedhighrisk, y = Percent_HighDTI))+
  geom_point()+
  theme_classic()+
  labs(x = '% of Census Tracts that are HNHR', y = '% of Mortgages with High DTI Ratios')+
  geom_text_repel(data = subset(weather_risk_florida, (highneedhighrisk>(median(highneedhighrisk)) & Percent_HighDTI>median(Percent_HighDTI))), aes(label = COUNTY), segment.color = 'grey80', colour = "red")+
  geom_vline(data = Florida_median, mapping = aes(xintercept = medhighneedhighrisk))+
  geom_hline(data = Florida_median, mapping = aes(yintercept = medPercent_HighDTI))

```

```{r}
ggplot(data = weather_risk_florida, mapping = aes(x = highneedhighrisk, y = HIGHDTI_UPB_value_hnhr))+
  geom_point()+
  theme_classic()+
  labs(x = '% of Census Tracts that are HNHR', y = 'Value of High DTI Unpaid Principal Balance in HNHR Tracts')+
  geom_text_repel(data = subset(weather_risk_florida, (highneedhighrisk>(median(highneedhighrisk)) & HIGHDTI_UPB_value_hnhr>median(HIGHDTI_UPB_value_hnhr))), aes(label = COUNTY), segment.color = 'grey80', colour = "red")+
  geom_vline(data = Florida_median, mapping = aes(xintercept = medhighneedhighrisk))+
  geom_hline(data = Florida_median, mapping = aes(yintercept = medHIGHDTI_UPB_value_hnhr))+
  scale_y_continuous(labels=scales::dollar_format())
```

```{r}
ggplot(data = weather_risk_florida, mapping = aes(x = highneedhighrisk, y = HIGHDTI_UPB_value))+
  geom_point()+
  theme_classic()+
  labs(x = '% of Census Tracts that are HNHR', y = 'Value of High DTI Unpaid Principal Balance')+
  geom_text_repel(data = subset(weather_risk_florida, (highneedhighrisk>(median(highneedhighrisk)) & HIGHDTI_UPB_value>median(HIGHDTI_UPB_value))), aes(label = COUNTY), segment.color = 'grey80', colour = "red")+
  geom_vline(data = Florida_median, mapping = aes(xintercept = medhighneedhighrisk))+
  geom_hline(data = Florida_median, mapping = aes(yintercept = medHIGHDTI_UPB_value))+
  scale_y_continuous(labels=scales::dollar_format())
```

```{r}
weather_risk_california <- fema %>%
  filter(STATE=="California") %>% 
  group_by(COUNTY) %>% 
  summarise(
    FiveRisk = sum(ANYFIVERISK>0)/n()*100,
    MORTGAGE_VALUE = sum(Total_UPB),
    MORTGAGE_VALUE_hnhr = sum(Total_UPB[HIGHNEED_HIGHRISK>0]),
    HIGHDTI_UPB_value = sum(`Total High_DTI_UPB`),
    HIGHDTI_UPB_value_hnhr = sum(`Total High_DTI_UPB`[HIGHNEED_HIGHRISK>0]),
    Percent_HighDTI = sum(Total_DTIover45)/sum(MORTGAGE_COUNT)*100,
    highneedhighrisk = sum(HIGHNEED_HIGHRISK)/n()*100)

weather_risk_california
```

```{r}
topHNHRvalue <- weather_risk_california %>% 
  filter(MORTGAGE_VALUE_hnhr>500000000)
ggplot(data = topHNHRvalue, mapping = aes(x= MORTGAGE_VALUE_hnhr, y= fct_reorder(COUNTY,MORTGAGE_VALUE_hnhr)))+
  geom_col() + 
  theme_classic()+
  theme(axis.text.y = element_text(size=14, vjust = 0.2, hjust=0.2))+ 
  labs(
    x= "UPB Value in HNHR census tracts",
    y= "Counties")+
  geom_label(aes(label=scales::dollar(MORTGAGE_VALUE_hnhr)), position=position_dodge(width=0.9), hjust=1, vjust=-0.25)+
  guides(color=FALSE)+
  scale_x_continuous(labels=scales::dollar_format())
```


```{r}

California_median <- weather_risk_california %>% 
  summarise(medFiveRisk = median(FiveRisk),
            medMORTGAGE_VALUE = median(MORTGAGE_VALUE),
            medPercent_HighDTI = median(Percent_HighDTI),
            medhighneedhighrisk = median(highneedhighrisk),
            medMORTGAGE_VALUE_hnhr = median(MORTGAGE_VALUE_hnhr),
            medHIGHDTI_UPB_value = median(HIGHDTI_UPB_value),
            medHIGHDTI_UPB_value_hnhr = median(HIGHDTI_UPB_value_hnhr)
            )
view(California_median)

```


```{r}
ggplot(data = weather_risk_california, mapping = aes(x = FiveRisk, y = MORTGAGE_VALUE))+
  geom_point()+
  theme_classic()+
  labs(x = '% of Census Tracts with High Climate Risk', y = 'Value of Unpaid Principal Balance')+
  geom_text_repel(data = subset(weather_risk_california, (FiveRisk>(median(FiveRisk)) & MORTGAGE_VALUE>median(MORTGAGE_VALUE))), aes(label = COUNTY), segment.color = 'grey80', colour = "red")+
  geom_vline(data = California_median, mapping = aes(xintercept = medFiveRisk))+
  geom_hline(data = California_median, mapping = aes(yintercept = medMORTGAGE_VALUE))+
  scale_y_continuous(labels=scales::dollar_format())
```


```{r}
ggplot(data = weather_risk_california, mapping = aes(x = highneedhighrisk, y = Percent_HighDTI))+
  geom_point()+
  theme_classic()+
  labs(x = '% of Census Tracts that are HNHR', y = '% of Mortgages with High DTI Ratios')+
  geom_text_repel(data = subset(weather_risk_california, (highneedhighrisk>(median(highneedhighrisk)) & Percent_HighDTI>median(Percent_HighDTI))), aes(label = COUNTY), segment.color = 'grey80', colour = "red")+
  geom_vline(data = California_median, mapping = aes(xintercept = medhighneedhighrisk))+
  geom_hline(data = California_median, mapping = aes(yintercept = medPercent_HighDTI))
```
```{r}
ggplot(data = weather_risk_california, mapping = aes(x = highneedhighrisk, y = HIGHDTI_UPB_value_hnhr))+
  geom_point()+
  theme_classic()+
  labs(x = '% of Census Tracts that are HNHR', y = 'Value of High DTI Unpaid Principal Balance in HNHR Tracts')+
  geom_text_repel(data = subset(weather_risk_california, (highneedhighrisk>(median(highneedhighrisk)) & HIGHDTI_UPB_value_hnhr>median(HIGHDTI_UPB_value_hnhr))), aes(label = COUNTY), segment.color = 'grey80', colour = "red")+
  geom_vline(data = California_median, mapping = aes(xintercept = medhighneedhighrisk))+
  geom_hline(data = California_median, mapping = aes(yintercept = medHIGHDTI_UPB_value_hnhr))+
  scale_y_continuous(labels=scales::dollar_format())
```

```{r}
ggplot(data = weather_risk_california, mapping = aes(x = highneedhighrisk, y = HIGHDTI_UPB_value))+
  geom_point()+
  theme_classic()+
  labs(x = '% of Census Tracts that are HNHR', y = 'Value of High DTI Unpaid Principal Balance')+
  geom_text_repel(data = subset(weather_risk_california, (highneedhighrisk>(median(highneedhighrisk)) & HIGHDTI_UPB_value>median(HIGHDTI_UPB_value))), aes(label = COUNTY), segment.color = 'grey80', colour = "red")+
  geom_vline(data = California_median, mapping = aes(xintercept = medhighneedhighrisk))+
  geom_hline(data = California_median, mapping = aes(yintercept = medHIGHDTI_UPB_value))+
  scale_y_continuous(labels=scales::dollar_format())
```

